In [2]:
import numpy as np
np.set_printoptions(suppress=True)

In [8]:
#initializes a 2x3x5 tensor T
T = np.stack([np.stack([np.linspace(15*j+5*i+1,15*j+5*i+5,5) for i in range(3)]) for j in range(2)])
print('This is a 2x3x5 tensor T:')
print(T)
print()

#note that the trivial slice of T is simply T itself
print('This is the :,:,: slice of T:')
print(T[:,:,:])
print()

#slices T to isolate different matrices
print('This is the 0,:,: slice of T:')
print(T[0,:,:])
print()

print('This is the :,0,: slice of T:')
print(T[:,0,:])
print()

print('This is the :,:,0 slice of T:')
print(T[:,:,0])
print()

#slices T to isolate tensors without reducing the order
print('This is the :,0:2,: slice of T:')
print(T[:,0:2,:])
print()

print('This is the :,:,1:4 slice of T:')
print(T[:,:,1:4])
print()

print('This is the :,1:3,0:3 slice of T:')
print(T[:,1:3,0:3])
print()

#combines the two ideas to isolate specific segments of T
print('This is the 1,0:2,2:5 slice of T:')
print(T[1,0:2,2:5])
print()

print('This is the 0,2,0:2 slice of T:')
print(T[0,2,0:2])

This is a 2x3x5 tensor T:
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]

This is the :,:,: slice of T:
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]

This is the 0,:,: slice of T:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]

This is the :,0,: slice of T:
[[ 1.  2.  3.  4.  5.]
 [16. 17. 18. 19. 20.]]

This is the :,:,0 slice of T:
[[ 1.  6. 11.]
 [16. 21. 26.]]

This is the :,0:2,: slice of T:
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]]]

This is the :,:,1:4 slice of T:
[[[ 2.  3.  4.]
  [ 7.  8.  9.]
  [12. 13. 14.]]

 [[17. 18. 19.]
  [22. 23. 24.]
  [27. 28. 29.]]]

This is the :,1:3,0:3 slice of T:
[[[ 6.  7.  8.]
  [11. 12. 13.]]

 [[21. 22. 23.]
  [26. 27. 28.]]]

This is the 1,0:2,2:5 slice of T:
[[

In [7]:
#loads an array called images.npy from present working directory
loaded = np.load('images.npy')
print('This is the first image from an array called images.npy:')
print(loaded[0])
print()

#performs a transformation on the array
newImages = loaded * 2
print('This is the transformed first image:')
print(newImages[0])
print()

#saves the array under a different name
np.save('editedImages.npy', newImages)
print('the array has been saved as editedImages.npy')

This is the first image from an array called images.npy:
[[[ 13  14  16 ... 128 134 125]
  [ 15  14  17 ... 126 146 139]
  [ 16  17  17 ...  48 112 135]
  ...
  [ 92  97  98 ...  76  69  54]
  [ 90  94  97 ...  63  38  87]
  [ 89  96  99 ...  59  26 117]]

 [[ 22  23  24 ... 143 148 140]
  [ 21  23  25 ... 152 170 158]
  [ 24  25  25 ...  72 139 157]
  ...
  [ 75  78  79 ...  61  52  44]
  [ 75  77  79 ...  46  30  61]
  [ 73  77  80 ...  38  25  74]]

 [[ 10   9  10 ...  78  85  78]
  [ 10   9  11 ...  81  96  94]
  [ 10  11  12 ...  32  67  88]
  ...
  [ 56  58  58 ...  44  40  37]
  [ 56  57  59 ...  38  22  57]
  [ 55  58  61 ...  38  16  78]]]

This is the transformed first image:
[[[ 26  28  32 ...   0  12 250]
  [ 30  28  34 ... 252  36  22]
  [ 32  34  34 ...  96 224  14]
  ...
  [184 194 196 ... 152 138 108]
  [180 188 194 ... 126  76 174]
  [178 192 198 ... 118  52 234]]

 [[ 44  46  48 ...  30  40  24]
  [ 42  46  50 ...  48  84  60]
  [ 48  50  50 ... 144  22  58]
  ...
  [

In [11]:
#initializes a 3x2 matrix A
A = np.array([[1,1],[3,0],[2,1]])

#initializes a vector b of length 2
b = np.array([-1,2])

print('This is a 3x2 matrix A:')
print(A)
print()

print('This a length 2 vector b:')
print(b)
print()

#multiplies Ab
print('This is their product Ab:')
print(np.dot(A,b))
print()

#demonstrates the internal steps in calculating Ab
b1a1 = b[0] * np.transpose(A)[0]
print('This is the first value of b times the first column of A:')
print(b1a1)
print()

b2a2 = b[1] * np.transpose(A)[1]
print('This is the second value of b times the second column of A:')
print(b2a2)
print()

print('This is their sum:')
print(b1a1 + b2a2)
print()

This is a 3x2 matrix A:
[[1 1]
 [3 0]
 [2 1]]

This a length 2 vector b:
[-1  2]

This is their product Ab:
[ 1 -3  0]

This is the first value of b times the first column of A
[-1 -3 -2]

This is the second value of b times the second column of A
[2 0 2]

This is their sum:
[ 1 -3  0]



In [16]:
#initializes a 5x4 matrix A
A = np.array([[1,1,1,1],[1,0,1,0],[1,2,3,4],[0,0,0,0],[-1,1,-1,0]])
print('This is a 5x4 matrix A:')
print(A)
print()

#initializes a vector b of length 4
b = np.array([1,0,-1,2])
print('This is a length 4 vector b:')
print(b)
print()

#multiplies Ab
print('This is the product Ab:')
print(np.dot(A,b))
print()

#initializes a 6x6 identity matrix
I = np.eye(6)
print('This is a 6x6 identity matrix I:')
print(I)
print()

#initializes a vector v of length 6
v = np.linspace(-1,1,6)
print('This is a length 6 vector v:')
print(v)
print()

#multiplies Iv. Note the result of multiplication by the "identity matrix"
print('This is the product Iv:')
print(np.dot(I,v))
print()

#The next print statement would fail because it multiplies a 5x4 matrix A against a length 6 vector v
#print(np.dot(A,v))

This is a 5x4 matrix A:
[[ 1  1  1  1]
 [ 1  0  1  0]
 [ 1  2  3  4]
 [ 0  0  0  0]
 [-1  1 -1  0]]

This is a length 4 vector b:
[ 1  0 -1  2]

This is the product Ab:
[2 0 6 0 0]

This is a 6x6 identity matrix I:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

This is a length 6 vector v:
[-1.  -0.6 -0.2  0.2  0.6  1. ]

This is the product Iv:
[-1.  -0.6 -0.2  0.2  0.6  1. ]



ValueError: shapes (5,4) and (6,) not aligned: 4 (dim 1) != 6 (dim 0)

In [3]:
#initializes 2 2x2 matrices
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

print('This is the first matrix:')
print(matrix1)
print()

print('This is the second matrix:')
print(matrix2)
print()

print('This is their product:')

#multiplies the 2 matrices together
print(np.dot(matrix1,matrix2))

This is the first matrix:
[[1 2]
 [3 4]]

This is the second matrix:
[[5 6]
 [7 8]]

This is their product:
[[19 22]
 [43 50]]


In [8]:
#initializes a 2x3 matrix A
A = np.array([[1,0,1],[-1,1,0]])
print('This is a 2x3 matrix A:')
print(A)
print()

#initializes a 3x2 matrix B
B = np.array([[3,2],[4,1],[0,3]])
print('This is a 3x2 matrix B:')
print(B)
print()

#multiplies AB
print('This is the product AB:')
print(np.dot(A,B))
print()

#multiplies A*b1
Ab1 = np.dot(A,B[:,0])
print('This is the product A*b1:')
print(Ab1)
print()

#multiplies A*b2
Ab2 = np.dot(A,B[:,1])
print('This is the product A*b2:')
print(Ab2)
print()

#constructs [A*b1, A*b2]
Ab12 = np.stack([Ab1,Ab2], 1)
print('This is the matrix with columns A*b1 and A*b2:')
print(Ab12)
print()

#multiplies BA
print('This is the product BA:')
print(np.dot(B,A))

This is a 2x3 matrix A:
[[ 1  0  1]
 [-1  1  0]]

This is a 3x2 matrix B:
[[3 2]
 [4 1]
 [0 3]]

This is the product AB:
[[ 3  5]
 [ 1 -1]]

This is the product A*b1:
[3 1]

This is the product A*b2:
[ 5 -1]

This is the matrix with columns A*b1 and A*b2:
[[ 3  5]
 [ 1 -1]]

This is the product BA:
[[ 1  2  3]
 [ 3  1  4]
 [-3  3  0]]


In [12]:
#initializes a 4x3x2 tensor with the values from 1 to 24
t = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]],[[19,20],[21,22],[23,24]]])
print('This is t:')
print(t)

#prints the shape of the tensor t
print(t.shape)
print()

#note that to access a specific element, an index must be specified for each axis
print('These are some elements of t:')
print(t[0,0,0]) #element located in the first position of each axis
print(t[1,0,0]) #element located in the second position of first axis, first position of second and third axes
print(t[0,1,0]) #element located in the first position of first axis, second position of second axis, first position of third axis
print(t[0,0,1]) #element located in the first position of first and second axes, second position of third axis
print(t[3,2,1]) #element located in the fourth position of first axis, third position of second axis, and second position of third axis
print()

#initializes a 2x2x2x2x2 tensor with values from 1 to 32
b = np.array([[[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]],[[[[17,18],[19,20]],[[21,22],[23,24]]],[[[25,26],[27,28]],[[29,30],[31,32]]]]])
print('This is a big tensor\'s shape and values')
print(b.shape)
print(b)

This is t:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)

These are some elements of t:
1
7
3
2
24

This is a big tensor's shape and values
(2, 2, 2, 2, 2)
[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[17 18]
    [19 20]]

   [[21 22]
    [23 24]]]


  [[[25 26]
    [27 28]]

   [[29 30]
    [31 32]]]]]


In [10]:
#initializes a 2x2x5 tensor with the boolean value 0 in each position
z = np.zeros([2,2,5], dtype=bool)
print('This is a tensor of boolean zeroes:')
print(z)
print()

#initializes a 2x2x5 tensor with the 32-bit float value 1 in each position
o = np.ones([2,2,5], dtype=np.float32)
print('This is a tensor of 32-bit float ones:')
print(o)
print()

#initializes a 2x2x5 tensor with the 64-bit integer value of c in each position
c = 42
f = np.full([2,2,5], c, np.int64)
print('This is a tensor with a constant 64-bit integer value in each position:')
print(f)
print()

#initializes a 2x2x5 tensor with random values in each position
r = np.random.random([2,2,5])
print('This is a tensor with random values in each position:')
print(r)
print()

#constructs a tensor from other tensors
b = np.stack([z,o,f,r])
print('This is a tensor formed by stacking the others along a new axis:')
print(b)
print()

This is a tensor of boolean zeroes:
[[[False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]]]

This is a tensor of 32-bit float ones:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

This is a tensor with a constant 64-bit integer value in each position:
[[[42 42 42 42 42]
  [42 42 42 42 42]]

 [[42 42 42 42 42]
  [42 42 42 42 42]]]

This is a tensor with random values in each position:
[[[0.67459924 0.74631576 0.89576844 0.01781203 0.13265666]
  [0.24481219 0.24530857 0.88473939 0.78607478 0.46219525]]

 [[0.15423658 0.34155604 0.67848896 0.20305476 0.92578016]
  [0.99821186 0.52783223 0.88779227 0.49366631 0.22523579]]]

This is a tensor formed by stacking the others along a new axis:
[[[[ 0.          0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.          0.   

In [ ]:
#initializes a vector of length d with values interpolating between 0 and 100
d = 5
l = np.linspace(0,100,d)
print('This is a vector of fixed length with equally spaced values from 0 to 100')
print(l)
print()

#initializes a vector with values ranging between 0 and 100 with a step size of s
s = 5
a = np.arange(0,100,s)
print('This is a vector with equally spaced values of a fixed step size from 0 until 100')
print(a)
print()

#initializes a 5x5 identity matrix
i = np.eye(3)
print('This is an identity matrix:')
print(i)
print()

In [10]:
#initializes a 2x2x2 tensor with specified values
v = np.array([[[2,3.5],[4,2]],[[1.5,1],[2,1]]])
print('This is v:')
print(v)
print()

#constructs a new 2x2x2 tensor formed by adding 2 to each of the entries in v
vAdd = v + 2
print('This is v+2:')
print(vAdd)
print()

#constructs a new 2x2x2 tensor formed by subtracting 2 from each of the entries in v
vSubtract = v - 2
print('This is v-2:')
print(vSubtract)
print()

#constructs a new 2x2x2 tensor formed by multiplying each of the entries by 2
vMultiply = v * 2
print('This is v*2:')
print(vMultiply)
print()

#constructs a new 2x2x2 tensor formed by dividing each of the entries by 2
vDivide = v / 2
print('This is v/2: ')
print(vDivide)

This is v:
[[[2.  3.5]
  [4.  2. ]]

 [[1.5 1. ]
  [2.  1. ]]]

This is v+2:
[[[4.  5.5]
  [6.  4. ]]

 [[3.5 3. ]
  [4.  3. ]]]

This is v-2:
[[[ 0.   1.5]
  [ 2.   0. ]]

 [[-0.5 -1. ]
  [ 0.  -1. ]]]

This is v*2:
[[[4. 7.]
  [8. 4.]]

 [[3. 2.]
  [4. 2.]]]

This is v/2: 
[[[1.   1.75]
  [2.   1.  ]]

 [[0.75 0.5 ]
  [1.   0.5 ]]]


In [12]:
#assigns the name w to v, creating a shallow copy
w = v

#constructs a new tensor x with the values of v, creating a deep copy
x = np.copy(v)

print('This is v: ')
print(v)
print()

#adds 1 to each value in v
v += 1
print('This is v after adding 1')
print(v)
print()

#divides each value in v by 2
v /= 2
print('This is v after dividing by 2')
print(v)
print()

print('This is w, changed by the operations performed on v: ')
print(w)
print()

print('This is x, unchanged by the operations performed on v: ')
print(x)

This is v: 
[[[1.5  2.25]
  [2.5  1.5 ]]

 [[1.25 1.  ]
  [1.5  1.  ]]]

This is v after adding 1
[[[2.5  3.25]
  [3.5  2.5 ]]

 [[2.25 2.  ]
  [2.5  2.  ]]]

This is v after dividing by 2
[[[1.25  1.625]
  [1.75  1.25 ]]

 [[1.125 1.   ]
  [1.25  1.   ]]]

This is w, changed by the operations performed on v: 
[[[1.25  1.625]
  [1.75  1.25 ]]

 [[1.125 1.   ]
  [1.25  1.   ]]]

This is x, unchanged by the operations performed on v: 
[[[1.5  2.25]
  [2.5  1.5 ]]

 [[1.25 1.  ]
  [1.5  1.  ]]]


In [4]:
#defines two 2x3x2 tensors, S and T
S = np.array([[[1,0],[-2,1],[3,2]],[[-3,0],[2,2],[0,-1]]])
T = np.array([[[-2,4],[3,3],[-1,-1]],[[1,-3],[1,1],[2,1]]])
print('This is a 2x3x2 tensor S:')
print(S)
print()
print('This is a 2x3x2 tensor T:')
print(T)
print()

#element-wise operations between 2 tensors work the same way as the scalar operations
print('This is the sum of S and T:')
print(S+T)
print()

print('This is the difference of S and T:')
print(S-T)
print()

print('This is the element-wise product of S and T:')
print(S*T)
print()

print('This is the element-wise quotient of S and T:')
print(S/T)

This is a 2x3x2 tensor S:
[[[ 1  0]
  [-2  1]
  [ 3  2]]

 [[-3  0]
  [ 2  2]
  [ 0 -1]]]

This is a 2x3x2 tensor T:
[[[-2  4]
  [ 3  3]
  [-1 -1]]

 [[ 1 -3]
  [ 1  1]
  [ 2  1]]]

This is the sum of S and T:
[[[-1  4]
  [ 1  4]
  [ 2  1]]

 [[-2 -3]
  [ 3  3]
  [ 2  0]]]

This is the difference of S and T:
[[[ 3 -4]
  [-5 -2]
  [ 4  3]]

 [[-4  3]
  [ 1  1]
  [-2 -2]]]

This is the element-wise product of S and T:
[[[-2  0]
  [-6  3]
  [-3 -2]]

 [[-3  0]
  [ 2  2]
  [ 0 -1]]]

This is the element-wise quotient of S and T:
[[[-0.5         0.        ]
  [-0.66666667  0.33333333]
  [-3.         -2.        ]]

 [[-3.         -0.        ]
  [ 2.          2.        ]
  [ 0.         -1.        ]]]


In [45]:
#initializes a vector v of length 6
v = np.linspace(1,6,6)
print('This is a vector v:')
print(v)
print()

#sums the elements of v along the first axis
print('This is the sum of elements of v along its axis:')
print(np.sum(v, axis=0))
print()

#sums the elements of v along the first axis with a for-loop
sum = 0
for i in range(v.shape[0]):
    sum += v[i]
print('This is the sum of elements of v given by a for-loop:')
print(sum)
print()

#initializes a 2x3 matrix A
A = np.array([[1,2,3],[4,5,6]])
print('This is a matrix A:')
print(A)
print()

#sums the elements of A along the first axis
print('This is the sum of elements of A along the first axis:')
print(np.sum(A, axis=0))
print()

#sums the elements of A along the first axis with a for-loop
B = np.zeros(A.shape[1])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        B[j] += A[i,j]
print('This is the sum of elements of A along the first axis given by a for-loop:')
print(B)
print()

#sums the elements of A along the second axis
print('This is the sum of elements of A along the second axis:')
print(np.sum(A, axis=1))

This is a vector v:
[1. 2. 3. 4. 5. 6.]

This is the sum of elements of v along its axis:
21.0

This is the sum of elements of v given by a for-loop:
21.0

This is a matrix A:
[[1 2 3]
 [4 5 6]]

This is the sum of elements of A along the first axis:
[5 7 9]

This is the sum of elements of A along the first axis given by a for-loop:
[5. 7. 9.]

This is the sum of elements of A along the second axis:
[ 6 15]


In [5]:
#initializes a 3x2x2 tensor T with random values from 0 to 10
T = np.random.random([3,2,2]) * 10
print('This is a tensor T:')
print(T)
print()

#sums the elements of T
print('This is the sum of the elements of T:')
print(np.sum(T))
print()

#sums the elements of T along the first axis
print('This is the sum of the elements of T along the first axis:')
print(np.sum(T, axis=0))
print()

#sums the elements of T along the first axis with a for-loop
U = np.zeros([T.shape[1], T.shape[2]])
for i in range(T.shape[0]):
    for j in range(T.shape[1]):
        for k in range(T.shape[2]):
            U[j,k] += T[i,j,k]
print('This is the sum of the elements of T along the first axis given by a for-loop:')
print(U)
print()

#sums the elements of T along the second and third axes simultaneously
print('This is the sum of the elements of T along the second and third axes:')
print(np.sum(T, axis=(1,2)))
print()

#sums the elements of T along the second and third axes
V = np.zeros(T.shape[0])
for i in range(T.shape[0]):
    for j in range(T.shape[1]):
        for k in range(T.shape[2]):
            V[i] += T[i,j,k]
print('This is the sum of the elements of T along the second and third axes given by a for-loop:')
print(V)
print()

#multiplies the elements of T together
print('This is the product of the elements of T:')
print(np.prod(T))
print()

#multiplies the elements of T along the third axis
#this produces a 3x2 matrix consisting of the columns of each matrix of T element-wise multiplied together
print('This is the product of the elements of T along the third axis:')
print(np.prod(T, axis=2))
print()

#finds the maximum and minimum elements of T along the 2nd axis
#produces 3x2 matrices consisting of the maximal/minimal element of each column of the matrices composing T
print('This is maximum reduction of T along the second axis:')
print(np.max(T, axis=1))
print('This is the minimum reduction of T along the second axis:')
print(np.min(T, axis=1))
print()

#finds the average and median of the elements of T along the first axis
print('This is the average reduction of T along the first axis:')
print(np.mean(T, axis=0))
print('This is the median reduction of T along the first axis:')
print(np.median(T, axis=0))

This is a tensor T:
[[[2.48523472 9.86223838]
  [8.96018248 7.2557229 ]]

 [[4.0784559  5.05814377]
  [7.4412967  2.71377503]]

 [[8.96783869 2.51603674]
  [5.30091775 3.68707075]]]

This is the sum of the elements of T:
68.3269138122672

This is the sum of the elements of T along the first axis:
[[15.53152931 17.43641889]
 [21.70239694 13.65656868]]

This is the sum of the elements of T along the first axis given by a for-loop:
[[15.53152931 17.43641889]
 [21.70239694 13.65656868]]

This is the sum of the elements of T along the second and third axes:
[28.56337848 19.2916714  20.47186393]

This is the sum of the elements of T along the second and third axes given by a for-loop:
[28.56337848 19.2916714  20.47186393]

This is the product of the elements of T:
292743429.6851706

This is the product of the elements of T along the third axis:
[[24.5099772  65.01260118]
 [20.62941631 20.19400518]
 [22.56341159 19.54485881]]

This is maximum reduction of T along the second axis:
[[8.96018248

In [12]:
#generates a vector of length 6 with values from 0 to 1
v = np.linspace(0,5,6)
print('This is a vector v of length 6 with values from 0 to 1:')
print(v)
print()

#constructs a vector length 18 by tiling v
print('This is a vector of length 18 constructed by tiling v 3 times along its axis')
print(np.tile(v, 3))
print()

#constructs a 5x6 matrix by tiling v
print('This is a 6x6 matrix constructed by tiling v 6 times along a new first axis:')
print(np.tile(v, [5,1]))
print()

#constructs a 2x4x6 tensor by tiling v
print('This is a 2x4x6 tensor constructed by tiling v 2 times along a new first axis and 6 times along a new second axis:')
print(np.tile(v, [2,4,1]))
print()

#initializes a 6x6 matrix with values from 0 to 2
A = np.stack([np.linspace(i,i+5,6) for i in range(0,6,1)], axis=1)
print('This is a 6x6 matrix with values from 0 to 2:')
print(A)
print()

#constructs a 2x2x6x6 tensor with values formed by tiling A
print('This is a 2x2x6x6 tensor constructed by tiling A 2 times along two new axes:')
print(np.tile(A, [2,2,1,1]))

This is a vector v of length 6 with values from 0 to 1:
[0. 1. 2. 3. 4. 5.]

This is a vector of length 18 constructed by tiling v 3 times along its axis
[0. 1. 2. 3. 4. 5. 0. 1. 2. 3. 4. 5. 0. 1. 2. 3. 4. 5.]

This is a 6x6 matrix constructed by tiling v 6 times along a new first axis:
[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]

This is a 2x4x6 tensor constructed by tiling v 2 times along a new first axis and 6 times along a new second axis:
[[[0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]]

 [[0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]]]

This is a 6x6 matrix with values from 0 to 2:
[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.  7.]
 [ 3.  4.  5.  6.  7.  8.]
 [ 4.  5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9. 10.]]

This is a 2x2x6x6 tensor constructed by tiling A 2 times along two new axes:
[[[[ 0.  1.  2.  3.  4

In [5]:
#initializes 2 vectors, u and v, of length 3
u = np.array([[1,0,1]])
v = np.array([[-1,0,1]])
print('This is a vector u:')
print(u)
print()
print('This is a vector v:')
print(v)
print()

def euclideanDistance(a,b, debug=False):
    difference = a-b
    squaredDifference = difference * difference
    sum = np.sum(squaredDifference)
    distance = np.sqrt(sum)
    if(debug):
        print('The difference between a and b is ', difference)
        print('Square each of the elements of that difference to get ', squaredDifference)
        print('The sum of those squares is ', sum)
        print('The square root of the sum is ', distance)
        print('Therefore the euclidean distance is: ')
    return distance

#finds the euclidean distance between u and v
print('This is the euclidean distance between u and v:')
print(euclideanDistance(u, v, debug=True))
print()

This is a vector u:
[[1 0 1]]

This is a vector v:
[[-1  0  1]]

This is the euclidean distance between u and v:
The difference between a and b is  [[2 0 0]]
Square each of the elements of that difference to get  [[4 0 0]]
The sum of those squares is  4
The square root of the sum is  2.0
Therefore the euclidean distance is: 
2.0



In [9]:
#initializes two vectors, u and v, of length 4
u = np.array([[1,2,3,4]])
v = np.array([[-1,4,-3,5]])
print('This is a vector u:')
print(u)
print()
print('This is a vector v:')
print(v)
print()

#finds the euclidean distance between u and v
print('This is the euclidean distance between u and v:')
print(euclideanDistance(u, v, debug=True))
print()

This is a vector u:
[[1 2 3 4]]

This is a vector v:
[[-1  4 -3  5]]

This is the euclidean distance between u and v:
The difference between a and b is  [[ 2 -2  6 -1]]
Square each of the elements of that difference to get  [[ 4  4 36  1]]
The sum of those squares is  45
The square root of the sum is  6.708203932499369
Therefore the euclidean distance is: 
6.708203932499369



In [10]:
#initializes three vectors of length 4
u = np.array([[1,2,3,4]])
v = np.array([[-1,4,-3,5]])
w = np.array([[0,4,1,0]])
print('This is a vector u:')
print(u)
print()
print('This is a vector v:')
print(v)
print()
print('This is a vector w:')
print(w)
print()

#finds the euclidean distance between u and u
print('This is the euclidean distance between u and itself:')
print(euclideanDistance(u,u))
print()

#finds the euclidean distance between v and v
print('This is the euclidean distance between v and itself:')
print(euclideanDistance(v,v))
print()

#finds the euclidean distance between u and v
distanceUV = euclideanDistance(u,v)
print('This is the euclidean distance between u and v:')
print(distanceUV)
print()

#finds the euclidean distance between v and u
print('This is the euclidean distance between v and u:')
print(euclideanDistance(v,u))
print('Note that these two values are equal.')
print()

#finds the euclidean distance between u and w
distanceUW = euclideanDistance(u,w)
print('This is the euclidean distance between u and w:')
print(distanceUW)
print()

#finds the euclidean distance between w and v
distanceWV = euclideanDistance(w,v)
print('This is the euclidean distance between w and v:')
print(distanceWV)
print()

#sums the euclidean distance between u and v
print('This is the sum of those two distances:')
print(distanceUW + distanceWV)
print('Note the distance between u and v is less or equal to that sum:')
print(distanceUV)

This is a vector u:
[[1 2 3 4]]

This is a vector v:
[[-1  4 -3  5]]

This is a vector w:
[[0 4 1 0]]

This is the euclidean distance between u and itself:
0.0

This is the euclidean distance between v and itself:
0.0

This is the euclidean distance between u and v:
6.708203932499369

This is the euclidean distance between v and u:
6.708203932499369
Note that these two values are equal.

This is the euclidean distance between u and w:
5.0

This is the euclidean distance between w and v:
6.48074069840786

This is the sum of those two distances:
11.48074069840786
Note the distance between u and v is less or equal to that sum:
6.708203932499369


In [6]:
#initializes two vectors, u and v, of length 4
u = np.array([1,2,3,4])
v = np.array([-1,4,-3,5])
print('This is a vector u:')
print(u)
print()
print('This is a vector v:')
print(v)
print()

#finds the L1 norm of v
print('This is the L1 norm of v:')
print(np.linalg.norm(v,1))
print()

#finds the L1 norm of v manually
vAbs = np.abs(v)
print('This is the element-wise absolute value of v:')
print(vAbs)
print()

print('This is the sum of the absolute-valued elements:')
print(np.sum(vAbs))
print()

#finds the L2 norm of v
print('This is the L2 norm of v:')
print(np.linalg.norm(v,2))
print()

#finds the L2 norm of v manually
vSquare = v*v
print('This is the element-wise square of v:')
print(vSquare)
print()

vSum = np.sum(vSquare)
print('This is the sum of the squared elements:')
print(vSum)
print()

print('This is the square root of the sum:')
print(np.sqrt(vSum))
print()

#shows the relationship between L2 norm and euclidean distance
print('Note that the L2 norm of u-v is:')
print(np.linalg.norm(u-v,2))
print('while the euclidean distance between u and v is:')
print(euclideanDistance(u,v))

This is a vector u:
[1 2 3 4]

This is a vector v:
[-1  4 -3  5]

This is the L1 norm of v:
13.0

This is the element-wise absolute value of v:
[1 4 3 5]

This is the sum of the absolute-valued elements:
13

This is the L2 norm of v:
7.14142842854285

This is the element-wise square of v:
[ 1 16  9 25]

This is the sum of the squared elements:
51

This is the square root of the sum:
7.14142842854285

Note that the L2 norm of u-v is:
6.708203932499369
while the euclidean distance between u and v is:
6.708203932499369


In [22]:
#defines a mean squared error function
def MSE(A, B, debug=False):
    error = A-B
    squared = error * error
    mean = np.mean(squared)
    if debug:
        print('This is the error:')
        print(error)
        print('This is the squared error:')
        print(squared)
        print('This is the MSE:')
    return mean

#initializes 2 2x3x5 tensors S and T
S = np.stack([np.stack([np.linspace(-7*j+i,-7*j+i+4,5) for i in range(1,4)]) for j in range(2)])
T = np.stack([np.stack([np.linspace(-10*j+i+4,-10*j+i,5) for i in range(2,5)]) for j in range(2)])
print('This is a tensor S:')
print(S)
print('This is a tensor T:')
print(T)
print()

#calculates the MSE between S and T
print('Process for calculating MSE between S and T:')
print(MSE(S,T,debug=True))
print()
print('Note the square of the L2 norm of S-T divided by the number of elements of S-T is:')
print(np.linalg.norm((S-T).flatten(), 2) ** 2 / S.size)

This is a tensor S:
[[[ 1.  2.  3.  4.  5.]
  [ 2.  3.  4.  5.  6.]
  [ 3.  4.  5.  6.  7.]]

 [[-6. -5. -4. -3. -2.]
  [-5. -4. -3. -2. -1.]
  [-4. -3. -2. -1.  0.]]]
This is a tensor T:
[[[ 6.  5.  4.  3.  2.]
  [ 7.  6.  5.  4.  3.]
  [ 8.  7.  6.  5.  4.]]

 [[-4. -5. -6. -7. -8.]
  [-3. -4. -5. -6. -7.]
  [-2. -3. -4. -5. -6.]]]

Process for calculating MSE between S and T:
This is the error:
[[[-5. -3. -1.  1.  3.]
  [-5. -3. -1.  1.  3.]
  [-5. -3. -1.  1.  3.]]

 [[-2.  0.  2.  4.  6.]
  [-2.  0.  2.  4.  6.]
  [-2.  0.  2.  4.  6.]]]
This is the squared error:
[[[25.  9.  1.  1.  9.]
  [25.  9.  1.  1.  9.]
  [25.  9.  1.  1.  9.]]

 [[ 4.  0.  4. 16. 36.]
  [ 4.  0.  4. 16. 36.]
  [ 4.  0.  4. 16. 36.]]]
This is the MSE:
10.5

Note the square of the L2 norm of S-T divided by the number of elements of S-T is:
10.500000000000002


In [21]:
#defines a mean absolute error function
def MAE(A, B, debug=False):
    error = A-B
    absolute = np.abs(error)
    mean = np.mean(absolute)
    if debug:
        print('This is the error:')
        print(error)
        print('This is the absolute error:')
        print(absolute)
        print('This is the MAE:')
    return mean

#initializes 2 2x3x5 tensors S and T
S = np.stack([np.stack([np.linspace(-7*j+i,-7*j+i+4,5) for i in range(1,4)]) for j in range(2)])
T = np.stack([np.stack([np.linspace(-10*j+i+4,-10*j+i,5) for i in range(2,5)]) for j in range(2)])
print('This is a tensor S:')
print(S)
print('This is a tensor T:')
print(T)
print()

#calculates the MAE between S and T
print('Process for calculating MAE between S and T:')
print(MAE(S,T,debug=True))
print()
print('Note the L1 norm of S-T divided by the number of elements of S-T:')
print(np.linalg.norm((S-T).flatten(),1)/(S.size))

This is a tensor S:
[[[ 1.  2.  3.  4.  5.]
  [ 2.  3.  4.  5.  6.]
  [ 3.  4.  5.  6.  7.]]

 [[-6. -5. -4. -3. -2.]
  [-5. -4. -3. -2. -1.]
  [-4. -3. -2. -1.  0.]]]
This is a tensor T:
[[[ 6.  5.  4.  3.  2.]
  [ 7.  6.  5.  4.  3.]
  [ 8.  7.  6.  5.  4.]]

 [[-4. -5. -6. -7. -8.]
  [-3. -4. -5. -6. -7.]
  [-2. -3. -4. -5. -6.]]]

Process for calculating MAE between S and T:
This is the error:
[[[-5. -3. -1.  1.  3.]
  [-5. -3. -1.  1.  3.]
  [-5. -3. -1.  1.  3.]]

 [[-2.  0.  2.  4.  6.]
  [-2.  0.  2.  4.  6.]
  [-2.  0.  2.  4.  6.]]]
This is the absolute error:
[[[5. 3. 1. 1. 3.]
  [5. 3. 1. 1. 3.]
  [5. 3. 1. 1. 3.]]

 [[2. 0. 2. 4. 6.]
  [2. 0. 2. 4. 6.]
  [2. 0. 2. 4. 6.]]]
This is the MAE:
2.7

Note the L1 norm of S-T divided by the number of elements of S-T:
2.7
