In [1]:
import numpy as np

In [3]:
#initializes 2 2x2 matrices
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

print('This is the first matrix:')
print(matrix1)
print()

print('This is the second matrix:')
print(matrix2)
print()

print('This is their product:')

#multiplies the 2 matrices together
print(np.dot(matrix1,matrix2))

This is the first matrix:
[[1 2]
 [3 4]]

This is the second matrix:
[[5 6]
 [7 8]]

This is their product:
[[19 22]
 [43 50]]


In [9]:
#initializes a 4x3x2 tensor with the values from 1 to 24
t = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]],[[19,20],[21,22],[23,24]]])
print(t)

#prints the shape of the tensor t
print(t.shape)
print()

#initializes a 4x3x2 tensor with the value 0 in each position
u = np.zeros([4,3,2])
print(u)
print(u.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(4, 3, 2)



In [10]:
#initializes a 2x2x2 tensor with specified values
v = np.array([[[2,3.5],[4,2]],[[1.5,1],[2,1]]])
print('This is v:')
print(v)
print()

#constructs a new 2x2x2 tensor formed by adding 2 to each of the entries in v
vAdd = v + 2
print('This is v+2:')
print(vAdd)
print()

#constructs a new 2x2x2 tensor formed by subtracting 2 from each of the entries in v
vSubtract = v - 2
print('This is v-2:')
print(vSubtract)
print()

#constructs a new 2x2x2 tensor formed by multiplying each of the entries by 2
vMultiply = v * 2
print('This is v*2:')
print(vMultiply)
print()

#constructs a new 2x2x2 tensor formed by dividing each of the entries by 2
vDivide = v / 2
print('This is v/2: ')
print(vDivide)

This is v:
[[[2.  3.5]
  [4.  2. ]]

 [[1.5 1. ]
  [2.  1. ]]]

This is v+2:
[[[4.  5.5]
  [6.  4. ]]

 [[3.5 3. ]
  [4.  3. ]]]

This is v-2:
[[[ 0.   1.5]
  [ 2.   0. ]]

 [[-0.5 -1. ]
  [ 0.  -1. ]]]

This is v*2:
[[[4. 7.]
  [8. 4.]]

 [[3. 2.]
  [4. 2.]]]

This is v/2: 
[[[1.   1.75]
  [2.   1.  ]]

 [[0.75 0.5 ]
  [1.   0.5 ]]]


In [12]:
#assigns the name w to v, creating a shallow copy
w = v

#constructs a new tensor x with the values of v, creating a deep copy
x = np.copy(v)

print('This is v: ')
print(v)
print()

#adds 1 to each value in v
v += 1
print('This is v after adding 1')
print(v)
print()

#divides each value in v by 2
v /= 2
print('This is v after dividing by 2')
print(v)
print()

print('This is w, changed by the operations performed on v: ')
print(w)
print()

print('This is x, unchanged by the operations performed on v: ')
print(x)

This is v: 
[[[1.5  2.25]
  [2.5  1.5 ]]

 [[1.25 1.  ]
  [1.5  1.  ]]]

This is v after adding 1
[[[2.5  3.25]
  [3.5  2.5 ]]

 [[2.25 2.  ]
  [2.5  2.  ]]]

This is v after dividing by 2
[[[1.25  1.625]
  [1.75  1.25 ]]

 [[1.125 1.   ]
  [1.25  1.   ]]]

This is w, changed by the operations performed on v: 
[[[1.25  1.625]
  [1.75  1.25 ]]

 [[1.125 1.   ]
  [1.25  1.   ]]]

This is x, unchanged by the operations performed on v: 
[[[1.5  2.25]
  [2.5  1.5 ]]

 [[1.25 1.  ]
  [1.5  1.  ]]]
